export const IconName = [
  "alipay",
  "alipay-o",
  "android",
  "android-o",
  "angle-left",
  "angle-up",
  "angle-right",
  "angle-down",
  "angle-double-left",
  "angle-double-up",
  "angle-double-right",
  "angle-double-down",
  "arrow-left",
  "arrow-up",
  "arrow-right",
  "arrow-down",
  "apple",
  "apple-o",

  "bar-chart",
  "bar-chart-o",
  "bell",
  "bell-o",

  "calendar",
  "calendar-o",
  "camera",
  "camera-o",
  "caret-left",
  "caret-up",
  "caret-right",
  "caret-down",
  "chain-broken",
  "check",
  "check-circle",
  "check-circle-o",
  "clock",
  "clock-o",
  "close",
  "close-circle",
  "close-circle-o",
  "comment",
  "comment-o",
  "crying-face",
  "crying-face-o",

  "download-o",

  "edit",
  "edit-o",
  "envelope",
  "envelope-o",
  "error-circle",
  "error-circle-o",

  "file",
  "file-audio-o",
  "file-code-o",
  "file-excel-o",
  "file-o",
  "file-other-o",
  "file-pdf-o",
  "file-picture-o",
  "file-powerpoint-o",
  "file-text-o",
  "file-video-o",
  "file-word-o",
  "file-zip-o",
  "folder",
  "folder-o",
  "folder-open",
  "folder-open-o",

  "heart",
  "heart-o",
  "help-circle",
  "help-circle-o",
  "home",
  "home-o",

  "info-circle",
  "info-circle-o",

  "jurisdiction",
  "jurisdiction-shield",

  "line-chart",
  "line-chart-o",
  "loading-annual-ring",
  "loading-black-hole",
  "loading-drop",
  "loading-drop-circle",
  "loading-drop-line",
  "loading-fading",
  "loading-fading-full",
  "loading-fading-point",
  "loading-point-line",
  "loading-refresh",
  "loading-snakes",
  "link",
  "lock",
  "lock-o",

  "map-marker",
  "map-marker-o",
  "menu",
  "minus",
  "minus-circle",
  "minus-circle-o",
  "minus-square",
  "minus-square-o",
  "maximize",
  "minimize",
  "maximize-restore",
  "mobile-phone",
  "mobile-phone-o",
  "more",

  "next",
  "no-data",
  "node",

  "other",
  "other-o",

  "pause",
  "picture",
  "picture-o",
  "pie-chart",
  "pie-chart-o",
  "play",
  "plus",
  "plus-circle",
  "plus-circle-o",
  "plus-square",
  "plus-square-o",
  "power-off-o",
  "previous",
  "print-o",
  "qq",
  "qq-o",
  "qrcode-o",

  "radio-border-circle",
  "radio-checked-circle",
  "random-o",
  "recovery",
  "recovery-o",
  "refresh-o",
  "return-o",
  "revoke",
  "revoke-o",

  "save",
  "save-o",
  "scanning-o",
  "screen",
  "search",
  "search-minus",
  "search-minus-o",
  "search-o",
  "search-plus",
  "search-plus-o",
  "settings",
  "settings-o",
  "set-top-o",
  "share",
  "share-o",
  "smiling-face",
  "smiling-face-o",
  "sort",
  "sort-up",
  "sort-down",
  "star",
  "star-o",
  "stop",
  "success-circle",
  "success-circle-o",

  "taobao",
  "taobao-o",
  "theme",
  "theme-o",
  "thumbs-up",
  "thumbs-up-o",
  "time",
  "time-o",
  "trash",
  "trash-o",

  "unlock",
  "unlock-o",
  "upload-o",
  "user",
  "user-o",
  "users",
  "users-o",

  "video-camera",
  "video-camera-o",

  "warning-circle",
  "warning-circle-o",
  "weibo",
  "weibo-o"
];
