export const IconName = [
  "angle-left",
  "angle-up",
  "angle-right",
  "angle-down",
  "angle-double-left",
  "angle-double-up",
  "angle-double-right",
  "angle-double-down",
  "arrow-left",
  "arrow-up",
  "arrow-right",
  "arrow-down",

  "caret-left",
  "caret-up",
  "caret-right",
  "caret-down",
  "check",
  "check-circle",
  "check-circle-o",
  "close",
  "close-circle",
  "close-circle-o",
  "crying-face-circle",
  "crying-face-o",

  "error-circle",
  "error-circle-o",

  "file-audio-o",
  "file-code-o",
  "file-excel-o",
  "file-o",
  "file-other-o",
  "file-pdf-o",
  "file-picture-o",
  "file-powerpoint-o",
  "file-text-o",
  "file-video-o",
  "file-word-o",
  "file-zip-o",

  "help-circle",
  "help-circle-o",
  "home",
  "home-o",

  "info-circle",
  "info-circle-o",

  "lock",
  "lock-o",

  "minus",
  "minus-circle",
  "minus-circle-o",
  "minus-square",
  "minus-square-o",
  "mobile-phone",
  "mobile-phone-o",

  "plus",
  "plus-circle",
  "plus-circle-o",
  "plus-square",
  "plus-square-o",

  "screen",
  "search",
  "search-minus",
  "search-minus-o",
  "search-o",
  "search-plus",
  "search-plus-o",
  "smiling-face-circle",
  "smiling-face-o",
  "sort",
  "sort-up",
  "sort-down",
  "success-circle",
  "success-circle-o",

  "unlock",
  "unlock-o",
  "user",
  "user-o",
  "users",
  "users-o",

  "warning-circle",
  "warning-circle-o"
];
